apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: 1h
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: flux
    annotations:
      cluster-region: ${CLUSTER_REGION}
  distribution:
    version: "2.x"
    registry: ghcr.io/fluxcd
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
    - source-watcher
  cluster:
    type: kubernetes
    multitenant: true
    tenantDefaultServiceAccount: flux
    networkPolicy: true
    domain: cluster.local
  sync:
    kind: GitRepository
    url: https://github.com/controlplaneio-fluxcd/flux-operator.git
    ref: refs/heads/main
    path: config/terraform/clusters/staging

    # Uncomment the following lines if using GitHub App authentication with a private repository.
    # provider: github
    # pullSecret: flux-system
  kustomize:
    patches:
      - target:
          kind: Kustomization
          name: flux-system
        patch: |
          - op: add
            path: /spec/postBuild
            value:
              substituteFrom:
                - kind: ConfigMap
                  name: flux-runtime-info
