version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      actions:
        patterns:
          - "*"
    schedule:
      interval: "daily"
  - package-ecosystem: gomod
    directory: "/"
    groups:
      go:
        patterns:
          - "*"
    schedule:
      interval: "daily"
