version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      actions:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/cmd/cli"
    groups:
      cli-tools:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
