// Copyright 2026 Stefan Prodan.
// SPDX-License-Identifier: AGPL-3.0

package agentops

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"sigs.k8s.io/yaml"

	fluxcdv1 "github.com/controlplaneio-fluxcd/flux-operator/api/v1"
)

const (
	// DefaultSkillsDirName is the directory name for skills relative to .agents/.
	DefaultSkillsDirName = ".agents/skills"

	// DefaultGlobalSkillsDirName is the global skills directory path.
	DefaultGlobalSkillsDirName = "~/.config/agents/skills"

	// CatalogFileName is the name of the catalog spec file.
	CatalogFileName = "catalog.yaml"

	// CatalogLockFileName is the name of the catalog lock file.
	CatalogLockFileName = "catalog-lock.yaml"
)

// ProjectRoot returns the current working directory, which is the root
// of the project where skills and agent symlinks are managed.
func ProjectRoot() (string, error) {
	cwd, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("getting working directory: %w", err)
	}
	return cwd, nil
}

// DefaultSkillsDir resolves the skills directory to an absolute path
// relative to the current working directory. If the path exists, it
// verifies that it is a real directory (not a symlink).
func DefaultSkillsDir() (string, error) {
	cwd, err := ProjectRoot()
	if err != nil {
		return "", err
	}

	dir := filepath.Join(cwd, DefaultSkillsDirName)

	info, err := os.Lstat(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return dir, nil
		}
		return "", fmt.Errorf("checking skills directory: %w", err)
	}

	if info.Mode()&os.ModeSymlink != 0 {
		return "", fmt.Errorf("skills directory %s is a symlink", dir)
	}
	if !info.IsDir() {
		return "", fmt.Errorf("skills path %s is not a directory", dir)
	}

	return dir, nil
}

// LoadCatalog builds a catalog by reading the spec from catalog.yaml and the
// status from catalog-lock.yaml. The spec in catalog.yaml is authoritative;
// the spec stored in the lock file is ignored.
func LoadCatalog(dir string) (*fluxcdv1.AgentCatalog, error) {
	catalog := &fluxcdv1.AgentCatalog{}
	catalog.APIVersion = fluxcdv1.AgentGroupVersion.String()
	catalog.Kind = fluxcdv1.AgentCatalogKind

	// Read spec from catalog.yaml.
	specPath := filepath.Join(dir, CatalogFileName)
	if data, err := os.ReadFile(specPath); err != nil {
		if !os.IsNotExist(err) {
			return nil, fmt.Errorf("reading catalog: %w", err)
		}
	} else {
		if err := yaml.Unmarshal(data, catalog); err != nil {
			return nil, fmt.Errorf("parsing catalog: %w", err)
		}
	}

	// Read status from catalog-lock.yaml.
	lockPath := filepath.Join(dir, CatalogLockFileName)
	if data, err := os.ReadFile(lockPath); err != nil {
		if !os.IsNotExist(err) {
			return nil, fmt.Errorf("reading catalog lock: %w", err)
		}
	} else {
		var lock fluxcdv1.AgentCatalog
		if err := yaml.Unmarshal(data, &lock); err != nil {
			return nil, fmt.Errorf("parsing catalog lock: %w", err)
		}
		catalog.Status = lock.Status
	}

	return catalog, nil
}

// SaveCatalog atomically writes the catalog spec to catalog.yaml in the given directory.
func SaveCatalog(dir string, catalog *fluxcdv1.AgentCatalog) error {
	specOnly := struct {
		metav1.TypeMeta `json:",inline"`
		Spec            fluxcdv1.AgentCatalogSpec `json:"spec"`
	}{
		TypeMeta: catalog.TypeMeta,
		Spec:     catalog.Spec,
	}
	return atomicWriteYAML(dir, CatalogFileName, specOnly)
}

// SaveCatalogLock atomically writes the full catalog to catalog-lock.yaml in the given directory.
func SaveCatalogLock(dir string, catalog *fluxcdv1.AgentCatalog) error {
	return atomicWriteYAML(dir, CatalogLockFileName, catalog, catalogLockHeader)
}

const catalogLockHeader = "# This manifest was generated by flux-operator. DO NOT EDIT.\n"

// atomicWriteYAML marshals the value to YAML and atomically writes it to the named file.
// An optional header is prepended to the output.
func atomicWriteYAML(dir, fileName string, v any, header ...string) error {
	data, err := yaml.Marshal(v)
	if err != nil {
		return fmt.Errorf("marshaling %s: %w", fileName, err)
	}

	if len(header) > 0 && header[0] != "" {
		data = append([]byte(header[0]), data...)
	}

	tmpFile, err := os.CreateTemp(dir, "."+fileName+"-*")
	if err != nil {
		return fmt.Errorf("creating temp file: %w", err)
	}
	tmpName := tmpFile.Name()
	defer os.Remove(tmpName)

	if _, err := tmpFile.Write(data); err != nil {
		if closeErr := tmpFile.Close(); closeErr != nil {
			return fmt.Errorf("writing %s: %w (close error: %v)", fileName, err, closeErr)
		}
		return fmt.Errorf("writing %s: %w", fileName, err)
	}

	if err := tmpFile.Close(); err != nil {
		return fmt.Errorf("closing temp file: %w", err)
	}

	dst := filepath.Join(dir, fileName)
	if err := os.Rename(tmpName, dst); err != nil {
		return fmt.Errorf("renaming %s: %w", fileName, err)
	}

	return nil
}

// CheckSkillConflicts checks if any skill name in newSkillNames is already
// installed by a different source in the catalog.
func CheckSkillConflicts(catalog *fluxcdv1.AgentCatalog, repo string, newSkillNames []string) error {
	newSet := make(map[string]struct{}, len(newSkillNames))
	for _, name := range newSkillNames {
		newSet[name] = struct{}{}
	}

	repoID := fluxcdv1.RepositoryID(repo)
	var conflicts []string
	for _, entry := range catalog.Status.Inventory {
		if entry.ID == repoID {
			continue
		}
		for _, skill := range entry.Skills {
			if _, ok := newSet[skill.Name]; ok {
				conflicts = append(conflicts, fmt.Sprintf("%q (from %s)", skill.Name, entry.URL))
			}
		}
	}

	if len(conflicts) > 0 {
		return fmt.Errorf("skill name conflicts with other sources: %s", strings.Join(conflicts, ", "))
	}
	return nil
}
