version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    revive:
      rules:
        - name: comment-spacings
        - name: import-shadowing
        - name: use-any
        - name: unreachable-code
        - name: struct-tag
          arguments:
            - "json,inline"
        - name: file-header
          arguments:
            - "SPDX-License-Identifier: AGPL-3.0"
    staticcheck:
      checks:
        - all
        # Incorrect or missing package comment.
        # https://staticcheck.dev/docs/checks/#ST1000
        - -ST1000
        # Dot imports are discouraged.
        # https://staticcheck.dev/docs/checks/#ST1001
        - -ST1001
        # Use consistent method receiver names.
        # https://staticcheck.dev/docs/checks/#ST1016
        - -ST1016
        # Omit embedded fields from selector expression.
        # https://staticcheck.dev/docs/checks/#QF1008
        - -QF1008
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
        source: "^\\s*defer\\s+"
      - linters:
          - staticcheck
        source: "r\\.Requeue"
      - linters:
          - lll
        path: api/*
      - linters:
          - dupl
          - lll
          - goconst
        path: cmd/*
      - linters:
          - dupl
          - lll
        path: internal/*
      - linters:
          - dupl
          - lll
        path: test/*
      - linters:
          - goconst
        path: ".*_test\\.go$"
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
