apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: flux-operator-mcp
    newName: ghcr.io/controlplaneio-fluxcd/flux-operator-mcp
    newTag: v0.29.0
