name: e2e-olm

on:
  workflow_dispatch:
  push:
    branches: [ '*' ]
    paths:
    - 'config/olm/**'
    - 'test/olm/**'
    - '.github/workflows/e2e-olm.yaml'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      packages: write # for pushing and signing container images.
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Disk Cleanup
        uses: ./.github/actions/runner-cleanup
      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: 1.27.x
          cache-dependency-path: |
            **/go.sum
            **/go.mod
      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: web/package-lock.json
      - name: Build frontend
        run: make web-ci-install web-build
      - name: Setup Kubernetes
        uses: helm/kind-action@06c1ae10762d3b9c1644e7fe69596ae519e015a2 # v1.15.0
        with:
          version: v0.24.0
          cluster_name: kind
      - name: Setup QEMU
        uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1 # v4.4.0
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run OLM tests
        run: make test-olm-e2e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
